// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1BcDuaqAUf9zX9mecHvd8VueasS7wcUo',
    appId: '1:408160611859:web:24a98cad43e00f534419e6',
    messagingSenderId: '408160611859',
    projectId: 'oscar-duty-app',
    authDomain: 'oscar-duty-app.firebaseapp.com',
    storageBucket: 'oscar-duty-app.firebasestorage.app',
    measurementId: 'G-7FY01Q73GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZe7CApMa8kW2xHAXXe6lb6w1sE0bZcoE',
    appId: '1:408160611859:android:f409f63e74698c844419e6',
    messagingSenderId: '408160611859',
    projectId: 'oscar-duty-app',
    storageBucket: 'oscar-duty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCAX4DX4oW1LaetZ9NwhyGEK__7VTdFg0',
    appId: '1:408160611859:ios:d9125e1b606257874419e6',
    messagingSenderId: '408160611859',
    projectId: 'oscar-duty-app',
    storageBucket: 'oscar-duty-app.firebasestorage.app',
    iosBundleId: 'com.sa3eed.oscar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCAX4DX4oW1LaetZ9NwhyGEK__7VTdFg0',
    appId: '1:408160611859:ios:d9125e1b606257874419e6',
    messagingSenderId: '408160611859',
    projectId: 'oscar-duty-app',
    storageBucket: 'oscar-duty-app.firebasestorage.app',
    iosBundleId: 'com.sa3eed.oscar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1BcDuaqAUf9zX9mecHvd8VueasS7wcUo',
    appId: '1:408160611859:web:824f8c35636b75294419e6',
    messagingSenderId: '408160611859',
    projectId: 'oscar-duty-app',
    authDomain: 'oscar-duty-app.firebaseapp.com',
    storageBucket: 'oscar-duty-app.firebasestorage.app',
    measurementId: 'G-GGWXH056XH',
  );

}